LOGO_PATH = 'logo.png'

TTP_PORT = 8080
TTP_IP = "172.16.39.145"

BUFFER_SIZE = 2048
MAX_ALLOWED_CONNECTIONS = 10
SALT = "!@#$%^&*()"

LOGIN = "LOGIN"
REGISTER = "REGISTER"
GET = "GET"
RESPONSE = "RESPONSE"
BAD_REQUEST = "Bad Request"
OK = "OK"
GENERATE = "GENERATE"
REVOCATE = "REVOCATE"
SET = "SET"
KEY = "KEY"
ADDRESS = "ADDRESS"
CONTENT_LENGTH = "Content-Length: "
CRLF = "\r\n"

PRIAVTE_KEY = "privateKey"
PUBLIC_KEY = "publicKey_"
ADDRESS_FILE = "address_"
KEY_DIRECTORY = "Assets"

BLOCK_SIZE = 192